version: '3.9'
services:
  app:
    image: jenkins/jenkins:lts-jdk11
    user: root
    ports:
      - 8080:8080
    networks:
      - jenkins-network
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - /jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:/root/.ssh
      - /etc/hosts:/etc/hosts
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  jenkins-network:
    external: true